import type { CssRule, FeatureDef } from '../features/types';
import { attrForFeature, attrForMarker } from '../features/types';

function expandedRules(f: FeatureDef): CssRule[] {
  const marker: CssRule[] = f.js ? [{ selector: `[${attrForMarker(f.id)}]` }] : [];
  return [...marker, ...f.rules];
}

export function countRules(features: FeatureDef[]): number {
  return features.reduce(
    (n, f) =>
      n + expandedRules(f).reduce((m, r) => m + (r.paths?.length ?? 1), 0),
    0,
  );
}

export function generateCss(features: FeatureDef[]): string {
  const lines = [
    '/* GENERATED by scripts/generate-css.ts — do not edit. Regenerate: bun run generate */',
  ];
  for (const f of features) {
    const attr = `[${attrForFeature(f.id)}]`;
    for (const r of expandedRules(f)) {
      const guards = r.paths?.length
        ? r.paths.map((p) => `html${attr}[data-df-path="${p}"]`)
        : [`html${attr}`];
      for (const g of guards) {
        lines.push(`${g} ${r.selector} { display: none !important; }`);
      }
    }
  }
  return lines.join('\n') + '\n';
}
