import type { FeatureDef } from './types';

export const FB_FEATURES: FeatureDef[] = [
  {
    id: 'fb.feed',
    label: 'Hide news feed',
    group: 'core',
    default: true,
    rules: [{ selector: 'div[role="feed"]', paths: ['home'] }],
    verify: 'Open facebook.com — feed posts gone, nav/rails per their own toggles.',
    confidence: 'high',
  },
  {
    id: 'fb.reels',
    label: 'Hide Reels',
    group: 'core',
    default: true,
    rules: [
      { selector: 'a[href^="/reel"]' },
      { selector: 'div[role="main"]', paths: ['reels'] },
    ],
    verify: 'Reels links gone everywhere; facebook.com/reel/<id> shows empty page.',
    confidence: 'medium',
  },
  {
    id: 'fb.stories',
    label: 'Hide Stories',
    group: 'core',
    default: true,
    rules: [
      { selector: 'div[aria-label="Stories"]' },
      { selector: 'div[role="main"]', paths: ['stories'] },
    ],
    verify: 'Open facebook.com — stories row above feed gone.',
    confidence: 'medium',
  },
  {
    id: 'fb.watch',
    label: 'Hide Watch / Video',
    group: 'core',
    default: true,
    rules: [
      { selector: 'a[href^="/watch"]' },
      { selector: 'div[role="main"]', paths: ['watch'] },
    ],
    verify: 'Watch nav link gone; facebook.com/watch shows empty page.',
    confidence: 'medium',
  },
  {
    id: 'fb.suggested',
    label: 'Hide suggested posts & people',
    group: 'engagement',
    default: false,
    rules: [],
    js: {
      containerSelector: 'div[role="feed"]',
      unitSelector: ':scope > div',
      textAnchors: ['Suggested for you', 'People you may know', 'People You May Know'],
    },
    verify: 'Scroll feed — "Suggested for you" and "People you may know" units gone.',
    confidence: 'low',
  },
  {
    id: 'fb.likeCounts',
    label: 'Hide reaction counts',
    group: 'engagement',
    default: false,
    rules: [{ selector: 'span[aria-label*="reaction" i]' }],
    verify: 'Open a post — reaction count pill gone.',
    confidence: 'low',
  },
  {
    id: 'fb.comments',
    label: 'Hide comments',
    group: 'engagement',
    default: false,
    rules: [
      { selector: 'ul:has(> li div[role="article"])' },
      { selector: 'div[aria-label*="Comment by" i]' },
    ],
    verify: 'Open a post with comments — comment thread gone.',
    confidence: 'low',
  },
  {
    id: 'fb.notifBadges',
    label: 'Hide notification badges',
    group: 'notifications',
    default: false,
    rules: [{ selector: 'span[aria-label*="notification" i]' }],
    verify: 'Have an unread notification — red count badge gone.',
    confidence: 'low',
  },
  {
    id: 'fb.rightRail',
    label: 'Hide right rail (sponsored, contacts)',
    group: 'chrome',
    default: false,
    rules: [{ selector: 'div[role="complementary"]', paths: ['home'] }],
    verify: 'Open facebook.com wide — sponsored/contacts column gone.',
    confidence: 'high',
  },
  {
    id: 'fb.leftNav',
    label: 'Hide left-nav shortcuts',
    group: 'chrome',
    default: false,
    rules: [{ selector: 'div[role="navigation"][aria-label*="Shortcuts" i]' }],
    verify: 'Open facebook.com — left shortcuts column gone.',
    confidence: 'medium',
  },
];
