import type { FeatureDef } from './types';

export const IG_FEATURES: FeatureDef[] = [
  {
    id: 'ig.feed',
    label: 'Hide home feed',
    group: 'core',
    default: true,
    rules: [
      { selector: 'main [role="feed"]', paths: ['home'] },
      { selector: 'main article', paths: ['home'] },
    ],
    verify: 'Open instagram.com — feed posts gone, nav still visible.',
    confidence: 'medium',
  },
  {
    id: 'ig.reels',
    label: 'Hide Reels',
    group: 'core',
    default: true,
    rules: [
      { selector: 'a[href^="/reels"]' },
      { selector: 'main', paths: ['reels'] },
    ],
    verify: 'Reels nav link gone; instagram.com/reels/ shows empty page.',
    confidence: 'medium',
  },
  {
    id: 'ig.explore',
    label: 'Hide Explore',
    group: 'core',
    default: true,
    rules: [
      { selector: 'a[href^="/explore"]' },
      { selector: 'main', paths: ['explore'] },
    ],
    verify: 'Explore nav link gone; instagram.com/explore/ shows empty page.',
    confidence: 'medium',
  },
  {
    id: 'ig.stories',
    label: 'Hide Stories tray',
    group: 'core',
    default: true,
    rules: [
      { selector: 'main div:has(> ul li canvas)', paths: ['home'] },
      { selector: 'main', paths: ['stories'] },
    ],
    verify: 'Open instagram.com — story avatars row above feed gone.',
    confidence: 'low',
  },
  {
    id: 'ig.suggested',
    label: 'Hide suggested posts',
    group: 'engagement',
    default: false,
    rules: [],
    js: {
      containerSelector: 'main',
      unitSelector: 'article',
      textAnchors: ['Suggested for you', 'Suggested posts'],
    },
    verify: 'Scroll home feed — "Suggested for you" posts gone.',
    confidence: 'low',
  },
  {
    id: 'ig.likeCounts',
    label: 'Hide like counts',
    group: 'engagement',
    default: false,
    rules: [{ selector: 'a[href*="/liked_by/"]' }],
    verify: 'Open any feed post — "N likes" line gone.',
    confidence: 'low',
  },
  {
    id: 'ig.comments',
    label: 'Hide comments',
    group: 'engagement',
    default: false,
    rules: [{ selector: 'article ul:has(ul)' }],
    verify: 'Open a post detail — comment thread gone, caption stays.',
    confidence: 'low',
  },
  {
    id: 'ig.notifBadges',
    label: 'Hide notification badges',
    group: 'notifications',
    default: false,
    rules: [{ selector: 'span[aria-label*="notification" i]' }],
    verify: 'Have an unread notification — red badge on heart icon gone.',
    confidence: 'low',
  },
  {
    id: 'ig.sidebar',
    label: 'Hide suggested accounts sidebar',
    group: 'chrome',
    default: false,
    rules: [
      { selector: 'main div:has(> div a[href^="/explore/people"])', paths: ['home'] },
    ],
    verify: 'Wide window on instagram.com — right "Suggested for you" column gone.',
    confidence: 'low',
  },
];
